### ISSUE TITLE
window pops up but is blank.

### ISSUE THREAD

**Issue by SimonEnsemble** [jgreener64/Bio3DView.jl#1] opened 2018-07-05 03:51 UTC
upon `viewfile("blah/myxyz.xyz", "xyz")`, a window pops up that is white (blank) and the following is printed in my REPL. Any idea what is going on? Thanks.

```
WARNING: `invoke(f, (types...), ...)` is deprecated, use `invoke(f, Tuple{types...}, ...)` instead
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] #view#5(::Dict{String,Dict{String,String}}, ::Function, ::String, ::String) at /home/cokes/.julia/v0.6/Bio3DView/src/Bio3DView.jl:104
 [3] (::Bio3DView.#kw##view)(::Array{Any,1}, ::Bio3DView.#view, ::String, ::String) at ./<missing>:0
 [4] #viewfile#1(::Dict{String,Dict{String,String}}, ::Function, ::String, ::String) at /home/cokes/.julia/v0.6/Bio3DView/src/Bio3DView.jl:37
 [5] viewfile(::String, ::String) at /home/cokes/.julia/v0.6/Bio3DView/src/Bio3DView.jl:34
 [6] eval(::Module, ::Any) at ./boot.jl:235
 [7] eval_user_input(::Any, ::Base.REPL.REPLBackend) at ./REPL.jl:66
 [8] macro expansion at ./REPL.jl:97 [inlined]
 [9] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73
while loading no file, in expression starting on line 0
Blink.AtomShell.Window(2, Blink.AtomShell.Electron(Process(`/home/cokes/.julia/v0.6/Blink/deps/atom/electron /home/cokes/.julia/v0.6/Blink/src/AtomShell/main.js port 2463`, ProcessRunning), TCPSocket(RawFD(30) active, 0 bytes waiting), Dict{String,Any}(Pair{String,Any}("callback", Blink.#3))), Blink.Page(2, #undef, Dict{String,Any}(Pair{String,Any}("callback", Blink.#3)), Future(1, 1, 2, Nullable{Any}())))
```

**Comment by jgreener64** [comment] 2018-07-05 09:53
Yeah I'm getting a blank screen too in my Linux machine, I did the initial work on Windows and it seemed to work there. I think it's something to do with Blink reading JS from a file.

I'll update the README to say that this project might have to wait until Julia v1.0 is out and stable before it gets stabilised. The IJulia stuff seems to be okay though.

**Comment by SimonEnsemble** [comment] 2018-07-05 17:40
I'm getting a blank window in Jupyter Lab too.

**Comment by jgreener64** [comment] 2018-07-05 20:01
Okay thanks for the info I haven't tried it in Jupyter Lab yet.

**Comment by jgreener64** [comment] 2018-10-05 15:14
I have updated the project to Julia v1.0 and the above issues seem to be fixed when using the latest versions of packages (including a recent JupyterLab version). I have yet to test on Mac.

Please open another issue if something else crops up.

**Comment by SimonEnsemble** [comment] 2018-10-05 19:32
I get `WARNING: could not import Base.quit into AtomShell` and still get a blank window on Ubuntu in Jupyter Lab.

**Comment by jgreener64** [comment] 2018-10-05 19:51
Thanks for trying, annoyingly it's quite hard to debug these things from afar. This sounds like two separate issues though:
- A Blink.jl issue related to this: https://github.com/JunoLab/Blink.jl/issues/153. Does the window open with a structure in? If so we might have to ignore this warning for now.
- The JupyterLab issue fixed itself for me when I updated JupyterLab, are you on the latest 0.34.12 version (as found with `conda list`/`pip freeze`/similar)?

**Comment by SimonEnsemble** [comment] 2018-10-07 01:37
A window does open up, but it is blank.
I updated Jupyter lab to v. 0.35 but still a blank window.
Also in the Julia REPL I get a blank window.

**Comment by SimonEnsemble** [comment] 2018-10-07 01:58
and your package is needed, since this does not even bring up a window in IJulia!
```julia
using PyCall
@pyimport py3Dmol
p = py3Dmol.view(query="pdb:1ycr")
p[:setStyle](Dict("cartoon" => Dict("color" => "spectrum")))
p[:show]()
```

**Comment by SimonEnsemble** [comment] 2018-10-07 04:03
Odd. So this works:

```julia
s = """
11

C       -0.180226841      0.360945118     -1.120304970
C       -0.180226841      1.559292118     -0.407860970
C       -0.180226841      1.503191118      0.986935030
N       -0.180226841      0.360945118      1.685965030
C       -0.180226841     -0.781300882      0.986935030
C       -0.180226841     -0.837401882     -0.407860970
H       -0.180226841      0.360945118     -2.206546970
H       -0.180226841      2.517950118     -0.917077970
H       -0.180226841      2.421289118      1.572099030
H       -0.180226841     -1.699398882      1.572099030
H       -0.180226841     -1.796059882     -0.917077970
"""
viewstring(s, "xyz"; style=Style("sphere"))
```

but when I put the xyz string into a file `pyz.xyz`:
```julia
viewfile("pyz.xyz", "xyz"; style=Style("sphere"))
```
I get a blank screen (my original report).

If I read the file in as a string, it does work!
```julia
s = read("pyz.xyz", String)
viewstring(s, "xyz"; style=Style("sphere")) # voila
```

so it must have something to do with the `.xyz` file reading?

**Comment by jgreener64** [comment] 2018-10-07 21:13
Thanks for digging in to this. I couldn't reproduce the error on my system unfortunately. This implies it might be something to do with permissions or access to the file rather than the xyz file reading.

I have pushed up a check that throws an error if it can't find the file, could you repeat the above and report if it throws an error or still gives a blank screen?

Is the different behaviour for string and file reading also the case with IJulia? I can understand it being an issue in the REPL as string and file reading are done differently, but with IJulia the internal steps are to call `read("pyz.xyz", String)` and then call the same function as for strings, so it would be weird if there was different behaviour.

**Comment by jgreener64** [comment] 2018-10-08 15:36
Okay, forget what I just said. It was an issue with reading a relative rather than an absolute filepath.

I just pushed a fix - hopefully this should be fixed now.

**Comment by SimonEnsemble** [comment] 2018-10-09 19:47
Fixed, thanks!
One suggestion: I keep getting tripped up over
`viewfile("CC3.xyz", "xyz")` not working but `viewstring(s, "xyz"; style=Style("sphere"))` does. Usually the latter suggests a default argument, but it is required here. So maybe throw an error if you don't get a style or make it a non-optional argument?

**Comment by jgreener64** [comment] 2018-10-10 10:31
Ah I see, the default style as is only works for PDB files. I will implement different default styles based on the file type.

Let me know if you have any other usability suggestions like this!

**Comment by jgreener64** [comment] 2018-10-10 11:16
Sensible default styles implemented (apart from for cube).

**Closed as completed** 2018-10-15 14:54 UTC
